# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved. 
# SPDX-License-Identifier: MIT-0

---
apiVersion: v1
kind: Namespace
metadata:
  name: k8multi
  labels:
    mesh: k8multi
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: k8multi
spec:
  namespaceSelector:
    matchLabels:
      mesh: k8multi
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: colorapp-blue
  namespace: k8multi
spec:
  podSelector:
    matchLabels:
      app: colorapp
      version: blue
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: svc2.svc.local
      serviceName: colorapp
      attributes:
      - key: color
        value: blue
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: colorapp-red
  namespace: k8multi
spec:
  podSelector:
    matchLabels:
      app: colorapp
      version: red
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: svc2.svc.local
      serviceName: colorapp
      attributes:
      - key: color
        value: red
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: colorapp
  namespace: k8multi
spec:
  awsName: colorapp.k8multi.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: colorapp-router
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: k8multi
  name: colorapp-router
spec:
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: color-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: colorapp-red
              weight: 1
            - virtualNodeRef:
                name: colorapp-blue
              weight: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorapp-blue
  namespace: k8multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorapp
      version: blue
  template:
    metadata:
      labels:
        app: colorapp
        version: blue
    spec:
      containers:
        - name: colorapp
          image: ECR_IMAGE_PREFIX/colorapp
          ports:
            - containerPort: 8080
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "COLOR"
              value: "blue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorapp-red
  namespace: k8multi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: colorapp
      version: red
  template:
    metadata:
      labels:
        app: colorapp
        version: red
    spec:
      containers:
        - name: colorapp
          image: ECR_IMAGE_PREFIX/colorapp
          ports:
            - containerPort: 8080
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "COLOR"
              value: "red"

